site_name: Project
# site_url: https://example.com/

docs_dir: docs/source
site_dir: docs/build
use_directory_urls: false # need for loading a static site

plugins:
  - mkdocstrings

theme:
  name: "material"