[build-system]
requires = ["setuptools >= 40.9.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/project -ra"""

[tool.pydocstyle]
convention = "google"